apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktroude-playground
  namespace: dev
  labels:
    app: ktroude-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktroude-playground
  template:
    metadata:
      labels:
        app: ktroude-playground
    spec:
      containers:
      - name: playground
        image: ktroude42/playground:v1
        ports:
        - containerPort: 8888
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5
---